using eveDirect.Shared.EsiConnector.Models;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace eveDirect.Shared.EsiConnector
{
    public static class EsiRequest
    {
        public enum RequestSecurity
        {
            Public,
            Authenticated
        }

        public enum RequestMethod
        {
            Delete,
            Get,
            Post,
            Put
        }
    }

    public static class RequestsInfo
    {
        public static readonly ImmutableDictionary<string, string> EndpointVersions = new Dictionary<string, string>()
        {
            {"Get|/alliances/", "v1"},
            {"Get|/alliances/{alliance_id}/", "v3"},
            {"Get|/alliances/{alliance_id}/contacts/", "v2"},
            {"Get|/alliances/{alliance_id}/contacts/labels/", "v1"},
            {"Get|/alliances/{alliance_id}/corporations/", "v1"},
            {"Get|/alliances/{alliance_id}/icons/", "v1"},
            {"Post|/characters/affiliation/", "v1"},
            {"Get|/characters/{character_id}/", "v4"},
            {"Get|/characters/{character_id}/agents_research/", "v1"},
            {"Get|/characters/{character_id}/assets/", "v3"},
            {"Post|/characters/{character_id}/assets/locations/", "v2"},
            {"Post|/characters/{character_id}/assets/names/", "v1"},
            {"Get|/characters/{character_id}/attributes/", "v1"},
            {"Get|/characters/{character_id}/blueprints/", "v2"},
            {"Get|/characters/{character_id}/bookmarks/", "v2"},
            {"Get|/characters/{character_id}/bookmarks/folders/", "v2"},
            {"Get|/characters/{character_id}/calendar/", "v1"},
            {"Get|/characters/{character_id}/calendar/{event_id}/", "v3"},
            {"Put|/characters/{character_id}/calendar/{event_id}/", "v3"},
            {"Get|/characters/{character_id}/calendar/{event_id}/attendees/", "v1"},
            {"Get|/characters/{character_id}/clones/", "v3"},
            {"Get|/characters/{character_id}/contacts/", "v2"},
            {"Post|/characters/{character_id}/contacts/", "v2"},
            {"Put|/characters/{character_id}/contacts/", "v2"},
            {"Delete|/characters/{character_id}/contacts/", "v2"},
            {"Get|/characters/{character_id}/contacts/labels/", "v1"},
            {"Get|/characters/{character_id}/contracts/", "v1"},
            {"Get|/characters/{character_id}/contracts/{contract_id}/bids/", "v1"},
            {"Get|/characters/{character_id}/contracts/{contract_id}/items/", "v1"},
            {"Get|/characters/{character_id}/corporationhistory/", "v1"},
            {"Post|/characters/{character_id}/cspa/", "v4"},
            {"Get|/characters/{character_id}/fatigue/", "v1"},
            {"Get|/characters/{character_id}/fittings/", "v2"},
            {"Post|/characters/{character_id}/fittings/", "v2"},
            {"Delete|/characters/{character_id}/fittings/{fitting_id}/", "v1"},
            {"Get|/characters/{character_id}/fleet/", "v1"},
            {"Get|/characters/{character_id}/fw/stats/", "v1"},
            {"Get|/characters/{character_id}/implants/", "v1"},
            {"Get|/characters/{character_id}/industry/jobs/", "v1"},
            {"Get|/characters/{character_id}/killmails/recent/", "v1"},
            {"Get|/characters/{character_id}/location/", "v1"},
            {"Get|/characters/{character_id}/loyalty/points/", "v1"},
            {"Get|/characters/{character_id}/mail/", "v1"},
            {"Post|/characters/{character_id}/mail/", "v1"},
            {"Get|/characters/{character_id}/mail/labels/", "v3"},
            {"Post|/characters/{character_id}/mail/labels/", "v2"},
            {"Delete|/characters/{character_id}/mail/labels/{label_id}/", "v1"},
            {"Get|/characters/{character_id}/mail/lists/", "v1"},
            {"Get|/characters/{character_id}/mail/{mail_id}/", "v1"},
            {"Put|/characters/{character_id}/mail/{mail_id}/", "v1"},
            {"Delete|/characters/{character_id}/mail/{mail_id}/", "v1"},
            {"Get|/characters/{character_id}/medals/", "v1"},
            {"Get|/characters/{character_id}/mining/", "v1"},
            {"Get|/characters/{character_id}/notifications/", "v5"},
            {"Get|/characters/{character_id}/notifications/contacts/", "v1"},
            {"Get|/characters/{character_id}/online/", "v2"},
            {"Get|/characters/{character_id}/opportunities/", "v1"},
            {"Get|/characters/{character_id}/orders/", "v2"},
            {"Get|/characters/{character_id}/orders/history/", "v1"},
            {"Get|/characters/{character_id}/planets/", "v1"},
            {"Get|/characters/{character_id}/planets/{planet_id}/", "v3"},
            {"Get|/characters/{character_id}/portrait/", "v2"},
            {"Get|/characters/{character_id}/roles/", "v2"},
            {"Get|/characters/{character_id}/search/", "v3"},
            {"Get|/characters/{character_id}/ship/", "v1"},
            {"Get|/characters/{character_id}/skillqueue/", "v2"},
            {"Get|/characters/{character_id}/skills/", "v4"},
            {"Get|/characters/{character_id}/standings/", "v1"},
            {"Get|/characters/{character_id}/stats/", "v2"},
            {"Get|/characters/{character_id}/titles/", "v1"},
            {"Get|/characters/{character_id}/wallet/", "v1"},
            {"Get|/characters/{character_id}/wallet/journal/", "v6"},
            {"Get|/characters/{character_id}/wallet/transactions/", "v1"},
            {"Get|/contracts/public/bids/{contract_id}/", "v1"},
            {"Get|/contracts/public/items/{contract_id}/", "v1"},
            {"Get|/contracts/public/{region_id}/", "v1"},
            {"Get|/corporation/{corporation_id}/mining/extractions/", "v1"},
            {"Get|/corporation/{corporation_id}/mining/observers/", "v1"},
            {"Get|/corporation/{corporation_id}/mining/observers/{observer_id}/", "v1"},
            {"Get|/corporations/npccorps/", "v1"},
            {"Get|/corporations/{corporation_id}/", "v4"},
            {"Get|/corporations/{corporation_id}/alliancehistory/", "v2"},
            {"Get|/corporations/{corporation_id}/assets/", "v3"},
            {"Post|/corporations/{corporation_id}/assets/locations/", "v2"},
            {"Post|/corporations/{corporation_id}/assets/names/", "v1"},
            {"Get|/corporations/{corporation_id}/blueprints/", "v2"},
            {"Get|/corporations/{corporation_id}/bookmarks/", "v1"},
            {"Get|/corporations/{corporation_id}/bookmarks/folders/", "v1"},
            {"Get|/corporations/{corporation_id}/contacts/", "v2"},
            {"Get|/corporations/{corporation_id}/contacts/labels/", "v1"},
            {"Get|/corporations/{corporation_id}/containers/logs/", "v2"},
            {"Get|/corporations/{corporation_id}/contracts/", "v1"},
            {"Get|/corporations/{corporation_id}/contracts/{contract_id}/bids/", "v1"},
            {"Get|/corporations/{corporation_id}/contracts/{contract_id}/items/", "v1"},
            {"Get|/corporations/{corporation_id}/customs_offices/", "v1"},
            {"Get|/corporations/{corporation_id}/divisions/", "v1"},
            {"Get|/corporations/{corporation_id}/facilities/", "v1"},
            {"Get|/corporations/{corporation_id}/fw/stats/", "v1"},
            {"Get|/corporations/{corporation_id}/icons/", "v1"},
            {"Get|/corporations/{corporation_id}/industry/jobs/", "v1"},
            {"Get|/corporations/{corporation_id}/killmails/recent/", "v1"},
            {"Get|/corporations/{corporation_id}/medals/", "v1"},
            {"Get|/corporations/{corporation_id}/medals/issued/", "v1"},
            {"Get|/corporations/{corporation_id}/members/", "v3"},
            {"Get|/corporations/{corporation_id}/members/limit/", "v1"},
            {"Get|/corporations/{corporation_id}/members/titles/", "v1"},
            {"Get|/corporations/{corporation_id}/membertracking/", "v1"},
            {"Get|/corporations/{corporation_id}/orders/", "v3"},
            {"Get|/corporations/{corporation_id}/orders/history/", "v2"},
            {"Get|/corporations/{corporation_id}/roles/", "v1"},
            {"Get|/corporations/{corporation_id}/roles/history/", "v1"},
            {"Get|/corporations/{corporation_id}/shareholders/", "v1"},
            {"Get|/corporations/{corporation_id}/standings/", "v1"},
            {"Get|/corporations/{corporation_id}/starbases/", "v1"},
            {"Get|/corporations/{corporation_id}/starbases/{starbase_id}/", "v1"},
            {"Get|/corporations/{corporation_id}/structures/", "v3"},
            {"Get|/corporations/{corporation_id}/titles/", "v1"},
            {"Get|/corporations/{corporation_id}/wallets/", "v1"},
            {"Get|/corporations/{corporation_id}/wallets/{division}/journal/", "v4"},
            {"Get|/corporations/{corporation_id}/wallets/{division}/transactions/", "v1"},
            {"Get|/dogma/attributes/", "v1"},
            {"Get|/dogma/attributes/{attribute_id}/", "v1"},
            {"Get|/dogma/dynamic/items/{type_id}/{item_id}/", "v1"},
            {"Get|/dogma/effects/", "v1"},
            {"Get|/dogma/effects/{effect_id}/", "v2"},
            {"Get|/fleets/{fleet_id}/", "v1"},
            {"Put|/fleets/{fleet_id}/", "v1"},
            {"Get|/fleets/{fleet_id}/members/", "v1"},
            {"Post|/fleets/{fleet_id}/members/", "v1"},
            {"Put|/fleets/{fleet_id}/members/{member_id}/", "v1"},
            {"Delete|/fleets/{fleet_id}/members/{member_id}/", "v1"},
            {"Put|/fleets/{fleet_id}/squads/{squad_id}/", "v1"},
            {"Delete|/fleets/{fleet_id}/squads/{squad_id}/", "v1"},
            {"Get|/fleets/{fleet_id}/wings/", "v1"},
            {"Post|/fleets/{fleet_id}/wings/", "v1"},
            {"Put|/fleets/{fleet_id}/wings/{wing_id}/", "v1"},
            {"Delete|/fleets/{fleet_id}/wings/{wing_id}/", "v1"},
            {"Post|/fleets/{fleet_id}/wings/{wing_id}/squads/", "v1"},
            {"Get|/fw/leaderboards/", "v1"},
            {"Get|/fw/leaderboards/characters/", "v1"},
            {"Get|/fw/leaderboards/corporations/", "v1"},
            {"Get|/fw/stats/", "v1"},
            {"Get|/fw/systems/", "v2"},
            {"Get|/fw/wars/", "v1"},
            {"Get|/incursions/", "v1"},
            {"Get|/industry/facilities/", "v1"},
            {"Get|/industry/systems/", "v1"},
            {"Get|/insurance/prices/", "v1"},
            {"Get|/killmails/{killmail_id}/{killmail_hash}/", "v1"},
            {"Get|/loyalty/stores/{corporation_id}/offers/", "v1"},
            {"Get|/markets/groups/", "v1"},
            {"Get|/markets/groups/{market_group_id}/", "v1"},
            {"Get|/markets/prices/", "v1"},
            {"Get|/markets/structures/{structure_id}/", "v1"},
            {"Get|/markets/{region_id}/history/", "v1"},
            {"Get|/markets/{region_id}/orders/", "v1"},
            {"Get|/markets/{region_id}/types/", "v1"},
            {"Get|/opportunities/groups/", "v1"},
            {"Get|/opportunities/groups/{group_id}/", "v1"},
            {"Get|/opportunities/tasks/", "v1"},
            {"Get|/opportunities/tasks/{task_id}/", "v1"},
            {"Get|/route/{origin}/{destination}/", "v1"},
            {"Get|/search/", "v2"},
            {"Get|/sovereignty/campaigns/", "v1"},
            {"Get|/sovereignty/map/", "v1"},
            {"Get|/sovereignty/structures/", "v1"},
            {"Get|/status/", "v1"},
            {"Post|/ui/autopilot/waypoint/", "v2"},
            {"Post|/ui/openwindow/contract/", "v1"},
            {"Post|/ui/openwindow/information/", "v1"},
            {"Post|/ui/openwindow/marketdetails/", "v1"},
            {"Post|/ui/openwindow/newmail/", "v1"},
            {"Get|/universe/ancestries/", "v1"},
            {"Get|/universe/asteroid_belts/{asteroid_belt_id}/", "v1"},
            {"Get|/universe/bloodlines/", "v1"},
            {"Get|/universe/categories/", "v1"},
            {"Get|/universe/categories/{category_id}/", "v1"},
            {"Get|/universe/constellations/", "v1"},
            {"Get|/universe/constellations/{constellation_id}/", "v1"},
            {"Get|/universe/factions/", "v2"},
            {"Get|/universe/graphics/", "v1"},
            {"Get|/universe/graphics/{graphic_id}/", "v1"},
            {"Get|/universe/groups/", "v1"},
            {"Get|/universe/groups/{group_id}/", "v1"},
            {"Post|/universe/ids/", "v1"},
            {"Get|/universe/moons/{moon_id}/", "v1"},
            {"Post|/universe/names/", "v3"},
            {"Get|/universe/planets/{planet_id}/", "v1"},
            {"Get|/universe/races/", "v1"},
            {"Get|/universe/regions/", "v1"},
            {"Get|/universe/regions/{region_id}/", "v1"},
            {"Get|/universe/schematics/{schematic_id}/", "v1"},
            {"Get|/universe/stargates/{stargate_id}/", "v1"},
            {"Get|/universe/stars/{star_id}/", "v1"},
            {"Get|/universe/stations/{station_id}/", "v2"},
            {"Get|/universe/structures/", "v1"},
            {"Get|/universe/structures/{structure_id}/", "v2"},
            {"Get|/universe/system_jumps/", "v1"},
            {"Get|/universe/system_kills/", "v2"},
            {"Get|/universe/systems/", "v1"},
            {"Get|/universe/systems/{system_id}/", "v4"},
            {"Get|/universe/types/", "v1"},
            {"Get|/universe/types/{type_id}/", "v3"},
            {"Get|/wars/", "v1"},
            {"Get|/wars/{war_id}/", "v1"},
            {"Get|/wars/{war_id}/killmails/", "v1" }
        }.ToImmutableDictionary();
        public static readonly ImmutableDictionary<string, string> EndpointSsoes = new Dictionary<string, string>() {
            {"Get|/characters/{character_id}/assets/", "esi-assets.read_assets.v1"},
            {"Post|/characters/{character_id}/assets/locations/", "esi-assets.read_assets.v1"},
            {"Post|/characters/{character_id}/assets/names/", "esi-assets.read_assets.v1"},
            {"Get|/characters/{character_id}/notifications/", "esi-characters.read_notifications.v1"},
            {"Get|/characters/{character_id}/wallet/journal/", "esi-wallet.read_character_wallet.v1"},
            {"Get|/corporations/{corporation_id}/assets/", "esi-assets.read_corporation_assets.v1"},
            {"Get|/alliances/{alliance_id}/contacts/", "esi-alliances.read_contacts.v1"},
            {"Get|/alliances/{alliance_id}/contacts/labels/", "esi-alliances.read_contacts.v1"},
            {"Get|/characters/{character_id}/agents_research/", "esi-characters.read_agents_research.v1"},
            {"Get|/characters/{character_id}/attributes/", "esi-skills.read_skills.v1"},
            {"Get|/characters/{character_id}/blueprints/", "esi-characters.read_blueprints.v1"},
            {"Get|/characters/{character_id}/bookmarks/", "esi-bookmarks.read_character_bookmarks.v1"},
            {"Get|/characters/{character_id}/bookmarks/folders/", "esi-bookmarks.read_character_bookmarks.v1"},
            {"Get|/characters/{character_id}/calendar/", "esi-calendar.read_calendar_events.v1"},
            {"Get|/characters/{character_id}/calendar/{event_id}/", "esi-calendar.read_calendar_events.v1"},
            {"Put|/characters/{character_id}/calendar/{event_id}/", "esi-calendar.respond_calendar_events.v1"},
            {"Get|/characters/{character_id}/calendar/{event_id}/attendees/", "esi-calendar.read_calendar_events.v1"},
            {"Get|/characters/{character_id}/clones/", "esi-clones.read_clones.v1"},
            {"Get|/characters/{character_id}/contacts/", "esi-characters.read_contacts.v1"},
            {"Post|/characters/{character_id}/contacts/", "esi-characters.write_contacts.v1"},
            {"Put|/characters/{character_id}/contacts/", "esi-characters.write_contacts.v1"},
            {"Delete|/characters/{character_id}/contacts/", "esi-characters.write_contacts.v1"},
            {"Get|/characters/{character_id}/contacts/labels/", "esi-characters.read_contacts.v1"},
            {"Get|/characters/{character_id}/contracts/", "esi-contracts.read_character_contracts.v1"},
            {"Get|/characters/{character_id}/contracts/{contract_id}/bids/", "esi-contracts.read_character_contracts.v1"},
            {"Get|/characters/{character_id}/contracts/{contract_id}/items/", "esi-contracts.read_character_contracts.v1"},
            {"Post|/characters/{character_id}/cspa/", "esi-characters.read_contacts.v1"},
            {"Get|/characters/{character_id}/fatigue/", "esi-characters.read_fatigue.v1"},
            {"Get|/characters/{character_id}/fittings/", "esi-fittings.read_fittings.v1"},
            {"Post|/characters/{character_id}/fittings/", "esi-fittings.write_fittings.v1"},
            {"Delete|/characters/{character_id}/fittings/{fitting_id}/", "esi-fittings.write_fittings.v1"},
            {"Get|/characters/{character_id}/fleet/", "esi-fleets.read_fleet.v1"},
            {"Get|/characters/{character_id}/fw/stats/", "esi-characters.read_fw_stats.v1"},
            {"Get|/characters/{character_id}/implants/", "esi-clones.read_implants.v1"},
            {"Get|/characters/{character_id}/industry/jobs/", "esi-industry.read_character_jobs.v1"},
            {"Get|/characters/{character_id}/killmails/recent/", "esi-killmails.read_killmails.v1"},
            {"Get|/characters/{character_id}/location/", "esi-location.read_location.v1"},
            {"Get|/characters/{character_id}/loyalty/points/", "esi-characters.read_loyalty.v1"},
            {"Get|/characters/{character_id}/mail/", "esi-mail.read_mail.v1"},
            {"Post|/characters/{character_id}/mail/", "esi-mail.send_mail.v1"},
            {"Get|/characters/{character_id}/mail/labels/", "esi-mail.read_mail.v1"},
            {"Post|/characters/{character_id}/mail/labels/", "esi-mail.organize_mail.v1"},
            {"Delete|/characters/{character_id}/mail/labels/{label_id}/", "esi-mail.organize_mail.v1"},
            {"Get|/characters/{character_id}/mail/lists/", "esi-mail.read_mail.v1"},
            {"Get|/characters/{character_id}/mail/{mail_id}/", "esi-mail.read_mail.v1"},
            {"Put|/characters/{character_id}/mail/{mail_id}/", "esi-mail.organize_mail.v1"},
            {"Delete|/characters/{character_id}/mail/{mail_id}/", "esi-mail.organize_mail.v1"},
            {"Get|/characters/{character_id}/medals/", "esi-characters.read_medals.v1"},
            {"Get|/characters/{character_id}/mining/", "esi-industry.read_character_mining.v1"},
            {"Get|/characters/{character_id}/notifications/contacts/", "esi-characters.read_notifications.v1"},
            {"Get|/characters/{character_id}/online/", "esi-location.read_online.v1"},
            {"Get|/characters/{character_id}/opportunities/", "esi-characters.read_opportunities.v1"},
            {"Get|/characters/{character_id}/orders/", "esi-markets.read_character_orders.v1"},
            {"Get|/characters/{character_id}/orders/history/", "esi-markets.read_character_orders.v1"},
            {"Get|/characters/{character_id}/planets/", "esi-planets.manage_planets.v1"},
            {"Get|/characters/{character_id}/planets/{planet_id}/", "esi-planets.manage_planets.v1"},
            {"Get|/characters/{character_id}/roles/", "esi-characters.read_corporation_roles.v1"},
            {"Get|/characters/{character_id}/search/", "esi-search.search_structures.v1"},
            {"Get|/characters/{character_id}/ship/", "esi-location.read_ship_type.v1"},
            {"Get|/characters/{character_id}/skillqueue/", "esi-skills.read_skillqueue.v1"},
            {"Get|/characters/{character_id}/skills/", "esi-skills.read_skills.v1"},
            {"Get|/characters/{character_id}/standings/", "esi-characters.read_standings.v1"},
            {"Get|/characters/{character_id}/stats/", "esi-characterstats.read.v1"},
            {"Get|/characters/{character_id}/titles/", "esi-characters.read_titles.v1"},
            {"Get|/characters/{character_id}/wallet/", "esi-wallet.read_character_wallet.v1"},
            {"Get|/characters/{character_id}/wallet/transactions/", "esi-wallet.read_character_wallet.v1"},
            {"Get|/corporation/{corporation_id}/mining/extractions/", "esi-industry.read_corporation_mining.v1"},
            {"Get|/corporation/{corporation_id}/mining/observers/", "esi-industry.read_corporation_mining.v1"},
            {"Get|/corporation/{corporation_id}/mining/observers/{observer_id}/", "esi-industry.read_corporation_mining.v1"},
            {"Post|/corporations/{corporation_id}/assets/locations/", "esi-assets.read_corporation_assets.v1"},
            {"Post|/corporations/{corporation_id}/assets/names/", "esi-assets.read_corporation_assets.v1"},
            {"Get|/corporations/{corporation_id}/blueprints/", "esi-corporations.read_blueprints.v1"},
            {"Get|/corporations/{corporation_id}/bookmarks/", "esi-bookmarks.read_corporation_bookmarks.v1"},
            {"Get|/corporations/{corporation_id}/bookmarks/folders/", "esi-bookmarks.read_corporation_bookmarks.v1"},
            {"Get|/corporations/{corporation_id}/contacts/", "esi-corporations.read_contacts.v1"},
            {"Get|/corporations/{corporation_id}/contacts/labels/", "esi-corporations.read_contacts.v1"},
            {"Get|/corporations/{corporation_id}/containers/logs/", "esi-corporations.read_container_logs.v1"},
            {"Get|/corporations/{corporation_id}/contracts/", "esi-contracts.read_corporation_contracts.v1"},
            {"Get|/corporations/{corporation_id}/contracts/{contract_id}/bids/", "esi-contracts.read_corporation_contracts.v1"},
            {"Get|/corporations/{corporation_id}/contracts/{contract_id}/items/", "esi-contracts.read_corporation_contracts.v1"},
            {"Get|/corporations/{corporation_id}/customs_offices/", "esi-planets.read_customs_offices.v1"},
            {"Get|/corporations/{corporation_id}/divisions/", "esi-corporations.read_divisions.v1"},
            {"Get|/corporations/{corporation_id}/facilities/", "esi-corporations.read_facilities.v1"},
            {"Get|/corporations/{corporation_id}/fw/stats/", "esi-corporations.read_fw_stats.v1"},
            {"Get|/corporations/{corporation_id}/industry/jobs/", "esi-industry.read_corporation_jobs.v1"},
            {"Get|/corporations/{corporation_id}/killmails/recent/", "esi-killmails.read_corporation_killmails.v1"},
            {"Get|/corporations/{corporation_id}/medals/", "esi-corporations.read_medals.v1"},
            {"Get|/corporations/{corporation_id}/medals/issued/", "esi-corporations.read_medals.v1"},
            {"Get|/corporations/{corporation_id}/members/", "esi-corporations.read_corporation_membership.v1"},
            {"Get|/corporations/{corporation_id}/members/limit/", "esi-corporations.track_members.v1"},
            {"Get|/corporations/{corporation_id}/members/titles/", "esi-corporations.read_titles.v1"},
            {"Get|/corporations/{corporation_id}/membertracking/", "esi-corporations.track_members.v1"},
            {"Get|/corporations/{corporation_id}/orders/", "esi-markets.read_corporation_orders.v1"},
            {"Get|/corporations/{corporation_id}/orders/history/", "esi-markets.read_corporation_orders.v1"},
            {"Get|/corporations/{corporation_id}/roles/", "esi-corporations.read_corporation_membership.v1"},
            {"Get|/corporations/{corporation_id}/roles/history/", "esi-corporations.read_corporation_membership.v1"},
            {"Get|/corporations/{corporation_id}/shareholders/", "esi-wallet.read_corporation_wallets.v1"},
            {"Get|/corporations/{corporation_id}/standings/", "esi-corporations.read_standings.v1"},
            {"Get|/corporations/{corporation_id}/starbases/", "esi-corporations.read_starbases.v1"},
            {"Get|/corporations/{corporation_id}/starbases/{starbase_id}/", "esi-corporations.read_starbases.v1"},
            {"Get|/corporations/{corporation_id}/structures/", "esi-corporations.read_structures.v1"},
            {"Get|/corporations/{corporation_id}/titles/", "esi-corporations.read_titles.v1"},
            {"Get|/corporations/{corporation_id}/wallets/", "esi-wallet.read_corporation_wallets.v1"},
            {"Get|/corporations/{corporation_id}/wallets/{division}/journal/", "esi-wallet.read_corporation_wallets.v1"},
            {"Get|/corporations/{corporation_id}/wallets/{division}/transactions/", "esi-wallet.read_corporation_wallets.v1"},
            {"Get|/fleets/{fleet_id}/", "esi-fleets.read_fleet.v1"},
            {"Put|/fleets/{fleet_id}/", "esi-fleets.write_fleet.v1"},
            {"Get|/fleets/{fleet_id}/members/", "esi-fleets.read_fleet.v1"},
            {"Post|/fleets/{fleet_id}/members/", "esi-fleets.write_fleet.v1"},
            {"Put|/fleets/{fleet_id}/members/{member_id}/", "esi-fleets.write_fleet.v1"},
            {"Delete|/fleets/{fleet_id}/members/{member_id}/", "esi-fleets.write_fleet.v1"},
            {"Put|/fleets/{fleet_id}/squads/{squad_id}/", "esi-fleets.write_fleet.v1"},
            {"Delete|/fleets/{fleet_id}/squads/{squad_id}/", "esi-fleets.write_fleet.v1"},
            {"Get|/fleets/{fleet_id}/wings/", "esi-fleets.read_fleet.v1"},
            {"Post|/fleets/{fleet_id}/wings/", "esi-fleets.write_fleet.v1"},
            {"Put|/fleets/{fleet_id}/wings/{wing_id}/", "esi-fleets.write_fleet.v1"},
            {"Delete|/fleets/{fleet_id}/wings/{wing_id}/", "esi-fleets.write_fleet.v1"},
            {"Post|/fleets/{fleet_id}/wings/{wing_id}/squads/", "esi-fleets.write_fleet.v1"},
            {"Get|/markets/structures/{structure_id}/", "esi-markets.structure_markets.v1"},
            {"Post|/ui/autopilot/waypoint/", "esi-ui.write_waypoint.v1"},
            {"Post|/ui/openwindow/contract/", "esi-ui.open_window.v1"},
            {"Post|/ui/openwindow/information/", "esi-ui.open_window.v1"},
            {"Post|/ui/openwindow/marketdetails/", "esi-ui.open_window.v1"},
            {"Post|/ui/openwindow/newmail/", "esi-ui.open_window.v1"},
            {"Get|/universe/structures/{structure_id}/", "esi-universe.read_structures.v1"},
        }.ToImmutableDictionary();
        public static readonly ImmutableDictionary<string, string[]> EndpointRoles = new Dictionary<string, string[]>() {
            {"Get|/corporation/{corporation_id}/mining/extractions/", new[] {"Station_Manager"}},
            {"Get|/corporation/{corporation_id}/mining/observers/", new[] {"Accountant"}},
            {"Get|/corporation/{corporation_id}/mining/observers/{observer_id}/", new[] {"Accountant"}},
            {"Get|/corporations/{corporation_id}/assets/", new[] {"Director"}},
            {"Post|/corporations/{corporation_id}/assets/locations/", new[] {"Director"}},
            {"Post|/corporations/{corporation_id}/assets/names/", new[] {"Director" }},
            {"Get|/corporations/{corporation_id}/blueprints/", new[] {"Director"}},
            {"Get|/corporations/{corporation_id}/containers/logs/", new[] {"Director"}},
            {"Get|/corporations/{corporation_id}/customs_offices/", new[] {"Director"}},
            {"Get|/corporations/{corporation_id}/divisions/", new[] {"Director"}},
            {"Get|/corporations/{corporation_id}/facilities/", new[] {"Factory_Manager"}},
            {"Get|/corporations/{corporation_id}/industry/jobs/", new[] {"Factory_Manager"}},
            {"Get|/corporations/{corporation_id}/killmails/recent/", new[] {"Director"}},
            {"Get|/corporations/{corporation_id}/medals/issued/", new[] {"Director"}},
            {"Get|/corporations/{corporation_id}/members/limit/", new[] {"Director"}},
            {"Get|/corporations/{corporation_id}/members/titles/", new[] {"Director"}},
            {"Get|/corporations/{corporation_id}/membertracking/", new[] {"Director"}},
            {"Get|/corporations/{corporation_id}/orders/", new[] {"Accountant", "Trader"}},
            {"Get|/corporations/{corporation_id}/orders/history/", new[] {"Accountant", "Trader"}},
            {"Get|/corporations/{corporation_id}/roles/history/", new[] {"Director"}},
            {"Get|/corporations/{corporation_id}/shareholders/", new[] {"Director"}},
            {"Get|/corporations/{corporation_id}/starbases/", new[] {"Director"}},
            {"Get|/corporations/{corporation_id}/starbases/{starbase_id}/", new[] {"Director"}},
            {"Get|/corporations/{corporation_id}/structures/", new[] {"Station_Manager"}},
            {"Get|/corporations/{corporation_id}/titles/", new[] {"Director" } },
            {"Get|/corporations/{corporation_id}/wallets/", new[] {"Accountant", "Junior_Accountant"}},
            {"Get|/corporations/{corporation_id}/wallets/{division}/journal/", new[] {"Accountant", "Junior_Accountant"}},
            {"Get|/corporations/{corporation_id}/wallets/{division}/transactions/", new[] {"Accountant", "Junior_Accountant"}}
        }.ToImmutableDictionary();
        public static readonly ImmutableDictionary<string, Type> EndpointRequestResults = new Dictionary<string, Type>()
        {
            {"Get|/alliances/", typeof(AlliancesResult) },
            {"Get|/alliances/{alliance_id}/", typeof(AllianceInfoResult) },
            {"Get|/alliances/{alliance_id}/corporations/", typeof(AlliancesCorporationsResult) },
            {"Get|/alliances/{alliance_id}/icons/", typeof(AllianceIconResult) },
            {"Get|/alliances/{alliance_id}/contacts/", typeof(AllianceContactsResult)},
            {"Get|/alliances/{alliance_id}/contacts/labels/", typeof(ContactsLabelsResult)},
            {"Post|/characters/affiliation/", typeof(CharacterAffiliationResult)},
            {"Get|/characters/{character_id}/", typeof(CharacterInfoResult)},
            {"Get|/characters/{character_id}/agents_research/", typeof(CharacterAgentsResearchResult)},
            {"Get|/characters/{character_id}/assets/", typeof(CharacterAssetsResult)},
            {"Post|/characters/{character_id}/assets/locations/", typeof(AssetLocationResult)},
            {"Post|/characters/{character_id}/assets/names/", typeof(AssetNameResult)},
            {"Get|/characters/{character_id}/attributes/", typeof(CharacterAttributesResult)},
            {"Get|/characters/{character_id}/blueprints/", typeof(CharacterBlueprintsResult)},
            {"Get|/characters/{character_id}/bookmarks/", typeof(BookmarksResult)},
            {"Get|/characters/{character_id}/bookmarks/folders/", typeof(CharacterBookmarksFoldersResult)},
            {"Get|/characters/{character_id}/calendar/", typeof(CharacterCalendarResult)},
            {"Get|/characters/{character_id}/calendar/{event_id}/", typeof(CharacterCalendarEventResult)},
            {"Get|/characters/{character_id}/calendar/{event_id}/attendees/", typeof(CharacterCalendarAttendeesResult)},
            {"Get|/characters/{character_id}/clones/", typeof(CharacterClonesResult)},
            {"Post|/characters/{character_id}/contacts/", typeof(List<int>)},
            {"Get|/characters/{character_id}/contacts/", typeof(CharacterContactsResult)},
            {"Get|/characters/{character_id}/contacts/labels/", typeof(ContactsLabelsResult)},
            {"Get|/characters/{character_id}/contracts/", typeof(CharacterContractsResult)},
            {"Get|/characters/{character_id}/contracts/{contract_id}/bids/", typeof(CharCorpContractsBidsResult)},
            {"Get|/characters/{character_id}/contracts/{contract_id}/items/", typeof(CharacterContractsItemsResult)},
            {"Get|/characters/{character_id}/corporationhistory/", typeof(CharacterCorporationHistoryResult)},
            {"Post|/characters/{character_id}/cspa/", typeof(float)},
            {"Get|/characters/{character_id}/fatigue/", typeof(CharacterFatigueResult)},
            {"Get|/characters/{character_id}/fittings/", typeof(CharacterFittingsResult)},
            {"Post|/characters/{character_id}/fittings/", typeof(CharacterFittingAddingResult)},
            {"Get|/characters/{character_id}/fleet/", typeof(CharacterFleetInfoResult)},
            {"Get|/characters/{character_id}/fw/stats/", typeof(CharacterFwStatsResult)},
            {"Get|/characters/{character_id}/implants/", typeof(CharacterImplantsResult)},
            {"Get|/characters/{character_id}/industry/jobs/", typeof(CharacterIndustryJobsResult)},
            {"Get|/characters/{character_id}/killmails/recent/", typeof(KillmailsRecentResult)},
            {"Get|/characters/{character_id}/location/", typeof(CharacterLocationResult)},
            {"Get|/characters/{character_id}/loyalty/points/", typeof(CharacterLoyaltyPointsResult)},
            {"Get|/characters/{character_id}/mail/", typeof(CharacterMailsResult)},
            {"Post|/characters/{character_id}/mail/", typeof(int)},
            {"Get|/characters/{character_id}/mail/labels/", typeof(CharacterMailLabelsResult)},
            {"Post|/characters/{character_id}/mail/labels/", typeof(int)},
            {"Get|/characters/{character_id}/mail/lists/", typeof(CharacterMailListsResult)},
            {"Get|/characters/{character_id}/mail/{mail_id}/", typeof(CharacterMailInfoResult)},
            {"Get|/characters/{character_id}/medals/", typeof(CharacterMedalsResult)},
            {"Get|/characters/{character_id}/mining/", typeof(CharacterIndustryMiningResult)},
            {"Get|/characters/{character_id}/notifications/", typeof(CharacterNotificationsResult)},
            {"Get|/characters/{character_id}/notifications/contacts/", typeof(CharacterNotificationsContactsResult)},
            {"Get|/characters/{character_id}/online/", typeof(CharacterOnlineResult)},
            {"Get|/characters/{character_id}/opportunities/", typeof(CharacterOpportunitiesResult)},
            {"Get|/characters/{character_id}/orders/", typeof(CharacterOrdersResult)},
            {"Get|/characters/{character_id}/orders/history/", typeof(CharacterOrdersHistoryResult)},
            {"Get|/characters/{character_id}/planets/", typeof(CharacterPlanetsResult)},
            {"Get|/characters/{character_id}/planets/{planet_id}/", typeof(CharactersPlanetColonyResult)},
            {"Get|/characters/{character_id}/portrait/", typeof(ImagesResult)},
            {"Get|/characters/{character_id}/roles/", typeof(CharacterRolesResult)},
            {"Get|/characters/{character_id}/search/", typeof(CharacterSearchResult)},
            {"Get|/characters/{character_id}/ship/", typeof(CharacterShipResult)},
            {"Get|/characters/{character_id}/skillqueue/", typeof(CharacterSkillqueueResult)},
            {"Get|/characters/{character_id}/skills/", typeof(CharacterSkillsResult)},
            {"Get|/characters/{character_id}/standings/", typeof(StandingsResult)},
            {"Get|/characters/{character_id}/stats/", typeof(CharacterStatResult)},
            {"Get|/characters/{character_id}/titles/", typeof(CharacterTitlesResult)},
            {"Get|/characters/{character_id}/wallet/", typeof(double)},
            {"Get|/characters/{character_id}/wallet/journal/", typeof(CharacterWalletJournalResult)},
            {"Get|/characters/{character_id}/wallet/transactions/", typeof(WalletTransactionsCharacterResult)},
            {"Get|/contracts/public/bids/{contract_id}/", typeof(ContractsBidsResult)},
            {"Get|/contracts/public/items/{contract_id}/", typeof(ContractsItemsResult)},
            {"Get|/contracts/public/{region_id}/", typeof(ContractsResult)},
            {"Get|/corporation/{corporation_id}/mining/extractions/", typeof(CorporationIndustryMiningExtractionsResult)},
            {"Get|/corporation/{corporation_id}/mining/observers/", typeof(CorporationIndustryMiningObserversResult)},
            {"Get|/corporation/{corporation_id}/mining/observers/{observer_id}/", typeof(CorporationIndustryMiningObserverItemResult)},
            {"Get|/corporations/npccorps/", typeof(CorporationNpccorpsResult)},
            {"Get|/corporations/{corporation_id}/", typeof(CorporationInfoResult)},
            {"Get|/corporations/{corporation_id}/alliancehistory/", typeof(CorporationAllianceHistoryResult)},
            {"Get|/corporations/{corporation_id}/assets/", typeof(CorporationAssetsResult)},
            {"Post|/corporations/{corporation_id}/assets/locations/", typeof(AssetLocationResult)},
            {"Post|/corporations/{corporation_id}/assets/names/", typeof(AssetsNamesResult)},
            {"Get|/corporations/{corporation_id}/blueprints/", typeof(CorporationBlueprintsResult)},
            {"Get|/corporations/{corporation_id}/bookmarks/", typeof(BookmarksResult)},
            {"Get|/corporations/{corporation_id}/bookmarks/folders/", typeof(CorporationBookmarksFoldersResult)},
            {"Get|/corporations/{corporation_id}/contacts/", typeof(CorporationContactsResult)},
            {"Get|/corporations/{corporation_id}/contacts/labels/", typeof(ContactsLabelsResult)},
            {"Get|/corporations/{corporation_id}/containers/logs/", typeof(CorporationContainersLogResult)},
            {"Get|/corporations/{corporation_id}/contracts/", typeof(CorporationContractsResult)},
            {"Get|/corporations/{corporation_id}/contracts/{contract_id}/bids/", typeof(CharCorpContractsBidsResult)},
            {"Get|/corporations/{corporation_id}/contracts/{contract_id}/items/", typeof(CorporationContractsItemsRresult)},
            {"Get|/corporations/{corporation_id}/customs_offices/", typeof(CorporationCustomOfficesResult)},
            {"Get|/corporations/{corporation_id}/divisions/", typeof(CorporationDivisionsResult)},
            {"Get|/corporations/{corporation_id}/facilities/", typeof(CorporationFacilitiesResult)},
            {"Get|/corporations/{corporation_id}/fw/stats/", typeof(CorporationFwStatsResult)},
            {"Get|/corporations/{corporation_id}/icons/", typeof(CorporationIconResult)},
            {"Get|/corporations/{corporation_id}/industry/jobs/", typeof(CorporationIndustryJobsResult)},
            {"Get|/corporations/{corporation_id}/killmails/recent/", typeof(KillmailsRecentResult)},
            {"Get|/corporations/{corporation_id}/medals/", typeof(CorporationMedalsResult)},
            {"Get|/corporations/{corporation_id}/medals/issued/", typeof(CorporationMedalsIssuedResult)},
            {"Get|/corporations/{corporation_id}/members/", typeof(CorporationMembersResult)},
            {"Get|/corporations/{corporation_id}/members/limit/", typeof(int)},
            {"Get|/corporations/{corporation_id}/members/titles/", typeof(CorporationMembersTitlesResult)},
            {"Get|/corporations/{corporation_id}/membertracking/", typeof(CorporationMembertrackingResult)},
            {"Get|/corporations/{corporation_id}/orders/", typeof(CorporationOrdersResult)},
            {"Get|/corporations/{corporation_id}/orders/history/", typeof(CorporationOrdersHistoryResult)},
            {"Get|/corporations/{corporation_id}/roles/", typeof(CorporationRolesResult)},
            {"Get|/corporations/{corporation_id}/roles/history/", typeof(CorporationRolesHistoryResult)},
            {"Get|/corporations/{corporation_id}/shareholders/", typeof(CorporationShareholdersResult)},
            {"Get|/corporations/{corporation_id}/standings/", typeof(StandingsResult)},
            {"Get|/corporations/{corporation_id}/starbases/", typeof(CorporationStarbasesResult)},
            {"Get|/corporations/{corporation_id}/starbases/{starbase_id}/", typeof(CorporationStarbasesInfoResult)},
            {"Get|/corporations/{corporation_id}/structures/", typeof(CorporationStructuresResult)},
            {"Get|/corporations/{corporation_id}/titles/", typeof(CorporationTitlesResult)},
            {"Get|/corporations/{corporation_id}/wallets/", typeof(CorporationWalletsResult)},
            {"Get|/corporations/{corporation_id}/wallets/{division}/journal/", typeof(CorporationWalletJournalResult)},
            {"Get|/corporations/{corporation_id}/wallets/{division}/transactions/", typeof(WalletTransactionsCorporationResult)},
            {"Get|/dogma/attributes/", typeof(DogmaAttributesResult)},
            {"Get|/dogma/attributes/{attribute_id}/", typeof(DogmaAttributeInfoResult)},
            {"Get|/dogma/dynamic/items/{type_id}/{item_id}/", typeof(DogmaDynamicItemResult)},
            {"Get|/dogma/effects/", typeof(DogmaEffectsResult)},
            {"Get|/dogma/effects/{effect_id}/", typeof(DogmaEffectInfoResult)},
            {"Get|/fleets/{fleet_id}/", typeof(FleetInfoResult)},
            {"Get|/fleets/{fleet_id}/members/", typeof(FleetMembersResult)},
            {"Get|/fleets/{fleet_id}/wings/", typeof(FleetWingsResult)},
            {"Post|/fleets/{fleet_id}/wings/", typeof(FleetAddingResult)},
            {"Post|/fleets/{fleet_id}/wings/{wing_id}/squads/", typeof(FleetAddingSquadResult)},
            {"Get|/fw/leaderboards/", typeof(TotalFwLeaderboardsResult)},
            {"Get|/fw/leaderboards/characters/", typeof(CharacterFwLeaderboardsResult)},
            {"Get|/fw/leaderboards/corporations/", typeof(CorporationFwLeaderboardsResult)},
            {"Get|/fw/stats/", typeof(FwStatsResult)},
            {"Get|/fw/systems/", typeof(FwSystemsResult)},
            {"Get|/fw/wars/", typeof(FwWarsResult)},
            {"Get|/incursions/", typeof(IncursionResult)},
            {"Get|/industry/facilities/", typeof(IndustryFacilitiesResult)},
            {"Get|/industry/systems/", typeof(IndustrySystemsResult)},
            {"Get|/insurance/prices/", typeof(InsurancePricesResult)},
            {"Get|/killmails/{killmail_id}/{killmail_hash}/", typeof(KillMailInfoResult)},
            {"Get|/loyalty/stores/{corporation_id}/offers/", typeof(LoyaltyStoresOffersResult)},
            {"Get|/markets/groups/", typeof(MarketsGroupsResult)},
            {"Get|/markets/groups/{market_group_id}/", typeof(MarketsGroupInfoResult)},
            {"Get|/markets/prices/", typeof(MarketsPricesResult)},
            {"Get|/markets/structures/{structure_id}/", typeof(MarketsStructureOrdersResult)},
            {"Get|/markets/{region_id}/history/", typeof(MarketsHistoryResult)},
            {"Get|/markets/{region_id}/orders/", typeof(MarketsOrdersResult)},
            {"Get|/markets/{region_id}/types/", typeof(MarketsTypesResult)},
            {"Get|/opportunities/groups/", typeof(OpportunitiesGroupsResult)},
            {"Get|/opportunities/groups/{group_id}/", typeof(OpportunitiesGroupInfoResult)},
            {"Get|/opportunities/tasks/", typeof(OpportunitiesTasksResult)},
            {"Get|/opportunities/tasks/{task_id}/", typeof(OpportunitiesTaskInfoResult)},
            {"Get|/route/{origin}/{destination}/", typeof(RouteInfoResult)},
            {"Get|/search/", typeof(SearchInfoResult)},
            {"Get|/sovereignty/campaigns/", typeof(SovereigntyCampaignsResult)},
            {"Get|/sovereignty/map/", typeof(SovereigntyMapsResult)},
            {"Get|/sovereignty/structures/", typeof(SovereigntyStructuresResult)},
            {"Get|/status/", typeof(StatusResult)},
            {"Get|/universe/ancestries/", typeof(UniverseAncestriesResult)},
            {"Get|/universe/asteroid_belts/{asteroid_belt_id}/", typeof(UniverseAsteroidBeltInfoResult)},
            {"Get|/universe/bloodlines/", typeof(UniverseBloodlinesResult)},
            {"Get|/universe/categories/", typeof(UniverseCategoriesResult)},
            {"Get|/universe/categories/{category_id}/", typeof(UniverseCategoryInfoResult)},
            {"Get|/universe/constellations/", typeof(UniverseConstellationsResult)},
            {"Get|/universe/constellations/{constellation_id}/", typeof(UniverseConstellationInfoResult)},
            {"Get|/universe/factions/", typeof(UniverseFactionsResult)},
            {"Get|/universe/graphics/", typeof(UniverseGraphicsResult)},
            {"Get|/universe/graphics/{graphic_id}/", typeof(UniverseGraphicInfoResult)},
            {"Get|/universe/groups/", typeof(UniverseGroupsResult)},
            {"Get|/universe/groups/{group_id}/", typeof(UniverseGroupInfoResult)},
            {"Post|/universe/ids/", typeof(UniverseIdResult)},
            {"Get|/universe/moons/{moon_id}/", typeof(UniverseMoonInfoResult)},
            {"Post|/universe/names/", typeof(UniverseNamesResult)},
            {"Get|/universe/planets/{planet_id}/", typeof(UniversePlanetInfoResult)},
            {"Get|/universe/races/", typeof(UniverseRacesResult)},
            {"Get|/universe/regions/", typeof(UniverseRegionsResult)},
            {"Get|/universe/regions/{region_id}/", typeof(UniverseRegionInfoResult)},
            {"Get|/universe/schematics/{schematic_id}/", typeof(UniverseSchematicInfoResult)},
            {"Get|/universe/stargates/{stargate_id}/", typeof(UniverseStargateInfoResult)},
            {"Get|/universe/stars/{star_id}/", typeof(UniverseStarInfoResult)},
            {"Get|/universe/stations/{station_id}/", typeof(UniverseStationInfoResult)},
            {"Get|/universe/structures/", typeof(UniverseStructuresResult)},
            {"Get|/universe/structures/{structure_id}/", typeof(UniverseStructureInfoResult)},
            {"Get|/universe/system_jumps/", typeof(UniverseSystemJumpsResult)},
            {"Get|/universe/system_kills/", typeof(UniverseSystemKillsResult)},
            {"Get|/universe/systems/", typeof(UniverseSystemsResult)},
            {"Get|/universe/systems/{system_id}/", typeof(UniverseSystemInfoResult)},
            {"Get|/universe/types/", typeof(UniverseTypesResult)},
            {"Get|/universe/types/{type_id}/", typeof(UniverseTypeInfoResult)},
            {"Get|/wars/", typeof(WarsResult)},
            {"Get|/wars/{war_id}/", typeof(WarInfoResult)},
            {"Get|/wars/{war_id}/killmails/", typeof(WarKillmailsResult)}
        }.ToImmutableDictionary();
    }

    public static class EsiErrorsCollect
    {
        /// <summary>
        /// Присотановленные запросы, которые не выполнились по сетевым ошибкам
        /// </summary>
        public static ConcurrentDictionary<string, DateTime> paused { get; set; } = new ConcurrentDictionary<string, DateTime>();

        public static ConcurrentDictionary<string, int> current_ErrorLimitRemain { get; set; } = new ConcurrentDictionary<string, int>();
        public static ConcurrentDictionary<string, int> current_ErrorLimitReset { get; set; } = new ConcurrentDictionary<string, int>();
    }
}