using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;


namespace eveDirect.Shared.EsiConnector.Models
{
    /// <summary>
    /// Результат GET /characters/{character_id}/notifications/
    /// </summary>
    public class CharacterNotificationsResult:List<CharacterNotificationsResult.CharacterNotificationsItem>, ISsoResult
    {
        public class CharacterNotificationsItem
        {
            public long notification_id { get; set; }
            public EType type { get; set; }
            public int sender_id { get; set; }
            public DateTime timestamp { get; set; }
            public bool is_read { get; set; }
            public string text { get; set; }
            public ESenderType sender_type { get; set; }
        }
        [System.Text.Json.Serialization.JsonConverter(typeof(eveDirect.Shared.Helper.JsonStringEnumMemberConverter))]
        public enum EType : byte
        {
            AcceptedAlly = 1,
            AcceptedSurrender = 2,
            AllAnchoringMsg = 3,
            AllMaintenanceBillMsg = 4,
            AllStrucInvulnerableMsg = 5,
            AllStructVulnerableMsg = 6,
            AllWarCorpJoinedAllianceMsg = 7,
            AllWarDeclaredMsg = 8,
            AllWarInvalidatedMsg = 9,
            AllWarRetractedMsg = 10,
            AllWarSurrenderMsg = 11,
            AllianceCapitalChanged = 12,
            AllianceWarDeclaredV2 = 13,
            AllyContractCancelled = 14,
            AllyJoinedWarAggressorMsg = 15,
            AllyJoinedWarAllyMsg = 16,
            AllyJoinedWarDefenderMsg = 17,
            BattlePunishFriendlyFire = 18,
            BillOutOfMoneyMsg = 19,
            BillPaidCorpAllMsg = 20,
            BountyClaimMsg = 21,
            BountyESSShared = 22,
            BountyESSTaken = 23,
            BountyPlacedAlliance = 24,
            BountyPlacedChar = 25,
            BountyPlacedCorp = 26,
            BountyYourBountyClaimed = 27,
            BuddyConnectContactAdd = 28,
            CharAppAcceptMsg = 29,
            CharAppRejectMsg = 30,
            CharAppWithdrawMsg = 31,
            CharLeftCorpMsg = 32,
            CharMedalMsg = 33,
            CharTerminationMsg = 34,
            CloneActivationMsg = 35,
            CloneActivationMsg2 = 36,
            CloneMovedMsg = 37,
            CloneRevokedMsg1 = 38,
            CloneRevokedMsg2 = 39,
            CombatOperationFinished = 40,
            ContactAdd = 41,
            ContactEdit = 42,
            ContainerPasswordMsg = 43,
            CorpAllBillMsg = 44,
            CorpAppAcceptMsg = 45,
            CorpAppInvitedMsg = 46,
            CorpAppNewMsg = 47,
            CorpAppRejectCustomMsg = 48,
            CorpAppRejectMsg = 49,
            CorpBecameWarEligible = 50,
            CorpDividendMsg = 51,
            CorpFriendlyFireDisableTimerCompleted = 52,
            CorpFriendlyFireDisableTimerStarted = 53,
            CorpFriendlyFireEnableTimerCompleted = 54,
            CorpFriendlyFireEnableTimerStarted = 55,
            CorpKicked = 56,
            CorpLiquidationMsg = 57,
            CorpNewCEOMsg = 58,
            CorpNewsMsg = 59,
            CorpNoLongerWarEligible = 60,
            CorpOfficeExpirationMsg = 61,
            CorpStructLostMsg = 62,
            CorpTaxChangeMsg = 63,
            CorpVoteCEORevokedMsg = 64,
            CorpVoteMsg = 65,
            CorpWarDeclaredMsg = 66,
            CorpWarDeclaredV2 = 67,
            CorpWarFightingLegalMsg = 68,
            CorpWarInvalidatedMsg = 69,
            CorpWarRetractedMsg = 70,
            CorpWarSurrenderMsg = 71,
            CustomsMsg = 72,
            DeclareWar = 73,
            DistrictAttacked = 74,
            DustAppAcceptedMsg = 75,
            EntosisCaptureStarted = 76,
            FWAllianceKickMsg = 77,
            FWAllianceWarningMsg = 78,
            FWCharKickMsg = 79,
            FWCharRankGainMsg = 80,
            FWCharRankLossMsg = 81,
            FWCharWarningMsg = 82,
            FWCorpJoinMsg = 83,
            FWCorpKickMsg = 84,
            FWCorpLeaveMsg = 85,
            FWCorpWarningMsg = 86,
            FacWarCorpJoinRequestMsg = 87,
            FacWarCorpJoinWithdrawMsg = 88,
            FacWarCorpLeaveRequestMsg = 89,
            FacWarCorpLeaveWithdrawMsg = 90,
            FacWarLPDisqualifiedEvent = 91,
            FacWarLPDisqualifiedKill = 92,
            FacWarLPPayoutEvent = 93,
            FacWarLPPayoutKill = 94,
            GameTimeAdded = 95,
            GameTimeReceived = 96,
            GameTimeSent = 97,
            GiftReceived = 98,
            IHubDestroyedByBillFailure = 99,
            IncursionCompletedMsg = 100,
            IndustryOperationFinished = 101,
            IndustryTeamAuctionLost = 102,
            IndustryTeamAuctionWon = 103,
            InfrastructureHubBillAboutToExpire = 104,
            InsuranceExpirationMsg = 105,
            InsuranceFirstShipMsg = 106,
            InsuranceInvalidatedMsg = 107,
            InsuranceIssuedMsg = 108,
            InsurancePayoutMsg = 109,
            InvasionSystemLogin = 110,
            JumpCloneDeletedMsg1 = 111,
            JumpCloneDeletedMsg2 = 112,
            KillReportFinalBlow = 113,
            KillReportVictim = 114,
            KillRightAvailable = 115,
            KillRightAvailableOpen = 116,
            KillRightEarned = 117,
            KillRightUnavailable = 118,
            KillRightUnavailableOpen = 119,
            KillRightUsed = 120,
            LocateCharMsg = 121,
            MadeWarMutual = 122,
            MercOfferRetractedMsg = 123,
            MercOfferedNegotiationMsg = 124,
            MissionOfferExpirationMsg = 125,
            MissionTimeoutMsg = 126,
            MoonminingAutomaticFracture = 127,
            MoonminingExtractionCancelled = 128,
            MoonminingExtractionFinished = 129,
            MoonminingExtractionStarted = 130,
            MoonminingLaserFired = 131,
            MutualWarExpired = 132,
            MutualWarInviteAccepted = 133,
            MutualWarInviteRejected = 134,
            MutualWarInviteSent = 135,
            NPCStandingsGained = 136,
            NPCStandingsLost = 137,
            OfferToAllyRetracted = 138,
            OfferedSurrender = 139,
            OfferedToAlly = 140,
            OldLscMessages = 141,
            OperationFinished = 142,
            OrbitalAttacked = 143,
            OrbitalReinforced = 144,
            OwnershipTransferred = 145,
            RaffleCreated = 146,
            RaffleExpired = 147,
            RaffleFinished = 148,
            ReimbursementMsg = 149,
            ResearchMissionAvailableMsg = 150,
            RetractsWar = 151,
            SeasonalChallengeCompleted = 152,
            SovAllClaimAquiredMsg = 153,
            SovAllClaimLostMsg = 154,
            SovCommandNodeEventStarted = 155,
            SovCorpBillLateMsg = 156,
            SovCorpClaimFailMsg = 157,
            SovDisruptorMsg = 158,
            SovStationEnteredFreeport = 159,
            SovStructureDestroyed = 160,
            SovStructureReinforced = 161,
            SovStructureSelfDestructCancel = 162,
            SovStructureSelfDestructFinished = 163,
            SovStructureSelfDestructRequested = 164,
            SovereigntyIHDamageMsg = 165,
            SovereigntySBUDamageMsg = 166,
            SovereigntyTCUDamageMsg = 167,
            StationAggressionMsg1 = 168,
            StationAggressionMsg2 = 169,
            StationConquerMsg = 170,
            StationServiceDisabled = 171,
            StationServiceEnabled = 172,
            StationStateChangeMsg = 173,
            StoryLineMissionAvailableMsg = 174,
            StructureAnchoring = 175,
            StructureCourierContractChanged = 176,
            StructureDestroyed = 177,
            StructureFuelAlert = 178,
            StructureItemsDelivered = 179,
            StructureItemsMovedToSafety = 180,
            StructureLostArmor = 181,
            StructureLostShields = 182,
            StructureOnline = 183,
            StructureServicesOffline = 184,
            StructureUnanchoring = 185,
            StructureUnderAttack = 186,
            StructureWentHighPower = 187,
            StructureWentLowPower = 188,
            StructuresJobsCancelled = 189,
            StructuresJobsPaused = 190,
            StructuresReinforcementChanged = 191,
            TowerAlertMsg = 192,
            TowerResourceAlertMsg = 193,
            TransactionReversalMsg = 194,
            TutorialMsg = 195,
            WarAdopted = 196,
            WarAllyInherited = 197,
            WarAllyOfferDeclinedMsg = 198,
            WarConcordInvalidates = 199,
            WarDeclared = 200,
            WarHQRemovedFromSpace = 201,
            WarInherited = 202,
            WarInvalid = 203,
            WarRetracted = 204,
            WarRetractedByConcord = 205,
            WarSurrenderDeclinedMsg = 206,
            WarSurrenderOfferMsg = 207,
        }
        [System.Text.Json.Serialization.JsonConverter(typeof(eveDirect.Shared.Helper.JsonStringEnumMemberConverter))]
        public enum ESenderType : byte
        {
            character = 1,
            corporation = 2,
            alliance = 3,
            faction = 4,
            other = 5
        }
    }
}
